# Generated by Django 5.1.7 on 2025-04-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slag',
            field=models.SlugField(editable=False, max_length=200, null=True, unique=True),
        ),
    ]
