# Generated by Django 5.1.7 on 2025-04-08 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_slag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='slag',
            new_name='slug',
        ),
    ]
